"""
setup_environment.py
CSC-114 Module 4 — California Housing Regression
Run this ONCE from E:\\test projects\\csc-114_tasks to install everything.

Python 3.14 note: TensorFlow and JAX have no 3.14 wheels yet.
This script uses PyTorch (CPU) as the Keras backend instead — it has
full 3.14 support and is the right call for a 480-sample dataset anyway.

Usage:
    cd "E:\\test projects\\csc-114_tasks"
    python setup_environment.py
"""

import subprocess
import sys
import os
from pathlib import Path

# ── Target directory (where THIS script lives) ────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent   # E:\test projects\csc-114_tasks

# ── Tell pip/Keras/PyTorch to cache here, NOT on C: ──────────────────────────
CACHE_DIR    = BASE_DIR / ".cache"
KERAS_DIR    = CACHE_DIR / "keras"
TORCH_DIR    = CACHE_DIR / "torch"
PIP_DIR      = CACHE_DIR / "pip"
DATASETS_DIR = BASE_DIR / "datasets"

for d in [CACHE_DIR, KERAS_DIR, TORCH_DIR, PIP_DIR, DATASETS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# Set env vars NOW so any imports below pick them up
os.environ["KERAS_HOME"]      = str(KERAS_DIR)
os.environ["KERAS_DATASETS"]  = str(DATASETS_DIR)
os.environ["KERAS_BACKEND"]   = "torch"
os.environ["PIP_CACHE_DIR"]   = str(PIP_DIR)
os.environ["TORCH_HOME"]      = str(TORCH_DIR)

# Write .env so the training script loads these paths at runtime
env_file = BASE_DIR / ".env"
env_content = f"""\
# Auto-generated by setup_environment.py
# Loaded automatically by california_housing_regression.py
KERAS_HOME={KERAS_DIR}
KERAS_DATASETS={DATASETS_DIR}
KERAS_BACKEND=torch
PIP_CACHE_DIR={PIP_DIR}
TORCH_HOME={TORCH_DIR}
"""
env_file.write_text(env_content)
print(f"[env]   .env written → {env_file}")

# ── Step 1: standard packages ─────────────────────────────────────────────────
STANDARD_PACKAGES = [
    "keras>=3.0,<3.9",
    "numpy",
    "matplotlib",
    "python-dotenv",
]

print("\n[pip]   Installing standard packages …")
result = subprocess.run([
    sys.executable, "-m", "pip", "install",
    "--cache-dir", str(PIP_DIR),
    "--upgrade",
] + STANDARD_PACKAGES)

if result.returncode != 0:
    print("\n[ERROR] Standard packages failed. Check output above.")
    sys.exit(1)

# ── Step 2: PyTorch CPU (needs its own index URL) ─────────────────────────────
# Python 3.14 only has CPU wheels for PyTorch right now.
# CPU is fine — this dataset is 480 rows, trains in minutes on CPU.
TORCH_INDEX = "https://download.pytorch.org/whl/cpu"

print(f"\n[pip]   Installing PyTorch (CPU build) from {TORCH_INDEX} …")
result = subprocess.run([
    sys.executable, "-m", "pip", "install",
    "--cache-dir", str(PIP_DIR),
    "--index-url", TORCH_INDEX,
    "torch",
])

if result.returncode != 0:
    print("\n[ERROR] PyTorch install failed. Check output above.")
    sys.exit(1)

print("\n[pip]   All packages installed.\n")

# ── Step 3: verify torch actually imported ────────────────────────────────────
print("[verify] Checking torch …")
verify = subprocess.run(
    [sys.executable, "-c", "import torch; print('  torch', torch.__version__)"],
    capture_output=True, text=True
)
print(verify.stdout.strip() if verify.returncode == 0 else "[WARN] torch import failed")

# ── Step 4: pre-download the dataset so training runs offline ─────────────────
print("\n[data]  Pre-fetching California Housing dataset …")
_kd  = str(KERAS_DIR).replace("\\", "/")
_dd  = str(DATASETS_DIR).replace("\\", "/")
fetch_script = f"""
import os
os.environ["KERAS_HOME"]     = r"{_kd}"
os.environ["KERAS_DATASETS"] = r"{_dd}"
os.environ["KERAS_BACKEND"]  = "torch"
import keras
from keras.datasets import california_housing
(tr, trt), (te, tet) = california_housing.load_data(version="small")
print(f"  Train {{tr.shape}}  Test {{te.shape}}")
print("  Cached -> {_dd}")
"""
result = subprocess.run([sys.executable, "-c", fetch_script],
                        capture_output=False)
if result.returncode != 0:
    print("[data]  WARNING: dataset fetch failed — it will download on first run.")

# ── Done ──────────────────────────────────────────────────────────────────────
print(f"""
┌──────────────────────────────────────────────────────────────┐
│  Setup complete                                              │
│                                                              │
│  Backend  : PyTorch CPU  (TF/JAX have no Python 3.14 wheels) │
│  Base dir : {str(BASE_DIR):<46}│
│  Cache    : {str(CACHE_DIR):<46}│
│  Datasets : {str(DATASETS_DIR):<46}│
│                                                              │
│  Next step: python california_housing_regression.py          │
└──────────────────────────────────────────────────────────────┘
""")